### ISSUE TITLE
Make pylint install optional

### ISSUE THREAD

**Issue by houblon** [houblon/pipenv_autoconfig#1]
@rudytrubitt, adding a "-l" argument sounds like a good solution. How much extra work is it to capture user input for that using "read"? Maybe after the script asks for the Python version, it could ask whether to install pylint, and use the value of that as a boolean. The script could first check for the -l argument, and if it's not there, ask the user whether to install pylint, as a default.

**Comment by rudytrubitt** [comment]
I forked the project and created a pull request.

**Comment by houblon** [comment]
Addressed with commit [c87145e](https://github.com/houblon/pipenv_autoconfig/commit/c87145eced7bde778533ce2e80c75175c72d491d)
